spring.application.name=api-gateway
server.port=8080

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://servicereg:8761/eureka/



spring.cloud.gateway.server.webmvc.routes[0].id=companyMicroservice
spring.cloud.gateway.server.webmvc.routes[0].uri=http://company:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/companies/**


spring.cloud.gateway.server.webmvc.routes[1].id=jobMicroservice
spring.cloud.gateway.server.webmvc.routes[1].uri=http://job:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/jobs/**

spring.cloud.gateway.server.webmvc.routes[2].id=reviewMicroservice
spring.cloud.gateway.server.webmvc.routes[2].uri=http://review:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/company/**

