JOBMICROSERVICE.url=http://job:8082
REVIEWMICROSERVICE.url=http://review:8083
COMPANYMICROSERVICE.url=http://company:8081

spring.application.name=jobMicroservice

server.port=8082
spring.mongodb.uri = mongodb+srv://sourabhbhattacharjee123:den3YFQ0rOARHp30@cluster0.v4monjx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=JobMicroserviceDB
spring.data.mongodb.auto-index-creation=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://servicereg:8761/eureka/


spring.cloud.config.enabled=false

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest