spring.application.name=companyMicroservice

server.port=8081

spring.mongodb.uri = mongodb+srv://sourabhbhattacharjee123:den3YFQ0rOARHp30@cluster0.v4monjx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=companyMicroserviceDB
spring.data.mongodb.auto-index-creation=true
